"""
Customer domain metadata and semantic definitions.
"""

CUSTOMER_METRICS = {
    "customer_retention_rate": "Percentage of customers who make repeat purchases.",
    "customer_lifetime_value": "Total revenue generated by a customer across all their orders.",
}

def get_customer_context() -> str:
    """Returns semantic context specifically for customer analysis."""
    context = "Customer Metrics Definitions:\n"
    for metric, desc in CUSTOMER_METRICS.items():
        context += f"- {metric}: {desc}\n"
    return context
