"""
Product domain metadata and semantic definitions.
"""

PRODUCT_METRICS = {
    "product_sales_volume": "Total quantity of a specific product sold.",
    "product_revenue": "Total revenue generated by a specific product.",
}

def get_product_context() -> str:
    """Returns semantic context specifically for product analysis."""
    context = "Product Metrics Definitions:\n"
    for metric, desc in PRODUCT_METRICS.items():
        context += f"- {metric}: {desc}\n"
    return context
