GOLD_ORDER_ITEM_FEATURE_GROUPS = {
    "delivery_logistics": [
        "customer_lat",
        "customer_lng",
        "seller_lat",
        "seller_lng",
        "delivery_distance_km",
        "delivery_days",
        "estimated_delivery_days",
        "delivery_delay_days",
        "shipping_processing_days",
        "carrier_handling_days",
        "delivery_distance_km_per_day",
        "delivery_efficiency_score",
        "is_delivered_late",
        "same_city_delivery",
        "same_state_delivery",
        "cross_region_delivery",
    ],
    "customer_behavior": [
        "customer_total_orders",
        "customer_total_spent",
        "customer_avg_order_value",
        "customer_lifetime_days",
        "customer_order_frequency",
        "customer_recency_days",
        "customer_recency_score",
        "customer_frequency_score",
        "customer_monetary_score",
        "customer_rfm_score",
    ],
    "seller_intelligence": [
        "seller_total_orders",
        "seller_total_revenue",
        "seller_unique_customers",
        "seller_avg_review_score",
        "seller_avg_delivery_delay",
        "seller_late_delivery_rate",
        "seller_revenue_rank",
    ],
    "product_intelligence": [
        "product_avg_review",
        "product_avg_shipping_cost",
        "product_volume_cm3",
        "product_density",
        "product_return_risk_proxy",
    ],
    "payment": [
        "is_installment_payment",
        "installment_count",
        "payment_complexity",
        "multi_payment_used",
        "payment_value_to_order_ratio",
    ],
}
